mongodb:
    host: beta-mongodb
    port: 27017
    user: dforcedev
    pass: 1234@dev

sql:
    host: beta-sql
    port: 3306
    user: dforcepro
    pass: 1234

elastic:
    host: beta-search
    port: 9200

redis:
    host: beta-redis:6379
    pass: ""
    db: 0

log:
    path: /var/log
    duration: hour   # day - hour - minute
    debug: true      # false(關閉) | true(開啟)

api:
    port: 9080
    middle:
        auth: true
        gen_doc: false
        log: false
        debug: true

    
rabbitmq:
    broker: 'amqp://rd:1234@beta-rabbitmq:5672/'
    default_queue: zbt_tasks
    result_backend: 'redis://beta-redis:6379'
    results_expire_in: 3600
    amqp:
        binding_key: zbt_tasks
        exchange: machinery_exchange
        exchange_type: direct
        prefetch_count: 3
